# Use the official .NET 8.0 SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-stage
WORKDIR /app

# Copy the .csproj file and restore any dependencies (via 'dotnet restore')
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the application and build it
COPY . ./
RUN dotnet publish -c Release -o out

# Use the official .NET 8.0 runtime image to run the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build-stage /app/out ./

# Configure the container to run the application
ENTRYPOINT ["dotnet", "TSPservice.dll"]

# Expose the ports your application is listening on
# (5000 for HTTP and 5001 for HTTPS)
EXPOSE 6000
 
