# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PointClustering.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15PointClustering.proto\"?\n\x0bMarkersData\x12\x1c\n\x07markers\x18\x01 \x03(\x0b\x32\x0b.MarkerData\x12\x12\n\nnumCluster\x18\x02 \x01(\x05\"-\n\x0f\x43lusterResponse\x12\x1a\n\x08\x63lusters\x18\x01 \x03(\x0b\x32\x08.Cluster\"&\n\nMarkerData\x12\x0b\n\x03Lat\x18\x02 \x01(\x01\x12\x0b\n\x03Lng\x18\x03 \x01(\x01\"+\n\x07\x43luster\x12 \n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32\x0b.Coordinate\"&\n\nCoordinate\x12\x0b\n\x03Lat\x18\x01 \x01(\x01\x12\x0b\n\x03Lng\x18\x02 \x01(\x01\x32?\n\x0fPointClustering\x12,\n\nClustering\x12\x0c.MarkersData\x1a\x10.ClusterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PointClustering_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKERSDATA']._serialized_start=25
  _globals['_MARKERSDATA']._serialized_end=88
  _globals['_CLUSTERRESPONSE']._serialized_start=90
  _globals['_CLUSTERRESPONSE']._serialized_end=135
  _globals['_MARKERDATA']._serialized_start=137
  _globals['_MARKERDATA']._serialized_end=175
  _globals['_CLUSTER']._serialized_start=177
  _globals['_CLUSTER']._serialized_end=220
  _globals['_COORDINATE']._serialized_start=222
  _globals['_COORDINATE']._serialized_end=260
  _globals['_POINTCLUSTERING']._serialized_start=262
  _globals['_POINTCLUSTERING']._serialized_end=325
# @@protoc_insertion_point(module_scope)
